export default {
  name: 'OpenJ9: gencon',
  memoryCalc: (vals) =>
    vals.maxHeap + vals.maxJitCodeCache + vals.maxJitDataCache
    + vals.maxDirectMemory + vals.maxClassStorage,
  parameters: [
    { key: 'maxHeap', label: 'Max heap', type: 'slider',
      unit: 'M',
      slider: { min: (vals) => vals.maxHeap / 2, max: (vals) => vals.maxHeap * 3, step: 16 },
      formatJvm: (v) => `-Xmx${v}m` },
    { key: 'maxNursery', label: 'Max nursery', type: 'slider',
      unit: 'M', slider: { min: 16, max: (vals) => vals.maxHeap * 0.5, step: 8 },
      formatJvm: (v) => `-Xmnx${v}m` },
    { key: 'maxTenured', label: 'Max tenured', type: 'derived',
      derive: (vals) => vals.maxHeap - vals.maxNursery,
      formatJvm: (v) => `-Xmox${v}m` },
    { key: 'maxJitCodeCache', label: 'JIT code cache', type: 'slider',
      unit: 'M', slider: { min: 16, max: 384, step: 8 },
      formatJvm: (v) => `-Xcodecachetotal${v}m` },
    { key: 'maxJitDataCache', label: 'JIT data cache', type: 'slider',
      unit: 'M', slider: { min: 16, max: 256, step: 8 },
      formatJvm: (v) => `-Xjit:datatotal=${v * 1024}` },
    { key: 'maxDirectMemory', label: 'Max direct memory', type: 'slider',
      unit: 'M', slider: { min: 16, max: 512, step: 16 },
      formatJvm: (v) => `-XX:MaxDirectMemorySize=${v}m` },
    { key: 'maxClassStorage', label: 'Class storage', type: 'slider',
      unit: 'M', slider: { min: 16, max: 256, step: 8 },
      formatJvm: () => null },
    { type: 'static', formatJvm: () => '-Djdk.nio.maxCachedBufferSize=262144' },
    { type: 'static', formatJvm: () => '-Xenableexplicitgc' },
    { type: 'static', formatJvm: () => '-XX:+PrintFlagsFinal', optional: true },
    { type: 'static', formatJvm: () => '-verbose:sizes', optional: true },
  ],
  presets: [
    { id: 1, name: 'dev', values: { maxHeap: 384, maxNursery: 96, maxJitCodeCache: 48, maxJitDataCache: 32, maxDirectMemory: 32, maxClassStorage: 160 } },
    { id: 2, name: 'prod - small', values: { maxHeap: 768, maxNursery: 192, maxJitCodeCache: 96, maxJitDataCache: 48, maxDirectMemory: 256, maxClassStorage: 160 } },
    { id: 3, name: 'prod - middle', values: { maxHeap: 2048, maxNursery: 512, maxJitCodeCache: 96, maxJitDataCache: 48, maxDirectMemory: 256, maxClassStorage: 160 } },
    { id: 4, name: 'prod - big', values: { maxHeap: 4096, maxNursery: 512, maxJitCodeCache: 96, maxJitDataCache: 48, maxDirectMemory: 256, maxClassStorage: 160 } },
  ],
}
